### ISSUE TITLE
Having blog.sourced.tech/firstnamelastname for each person

### ISSUE THREAD

**Issue by margaridag** [src-d/blog#100]
@marnovo let me know what you think about having one URL that redirects to all blog posts from each person/writer in the team.

It would be great for each personally so they can easily add it wherever they want (personal websites, twitter, CFPs sent, etc.) and for us to share with external people interested in a specific area as well.

If we want to do it even further, we could also have another URL per team as well :)

Let me know!

**Comment by margaridag** [comment]
@marnovo did you have time to look at this?

**Comment by marnovo** [comment]
@margaridag, yep I added your feature request to [features/issues/#241](https://github.com/src-d/features/issues/241) for discussion. Let's keep projects' repo issues just for problems or engineering workflow.

@src-d/platform please close this, svp!

**Comment by marnovo** [comment]
@dpordomingo close svp.

**Comment by dpordomingo** [comment]
@nativo I have no enough privileges. Maybe @mcuadros?
