### ISSUE TITLE
Standardize post specific assets location

### ISSUE THREAD

**Issue by Serabe** [src-d/blog#124]

**Comment by marnovo** [comment]
@dpordomingo please close this, already included in https://github.com/src-d/backlog/issues/1058

**Comment by dpordomingo** [comment]
@marnovo I have no privilege to close blog issues. Maybe @mcuadros?

**Comment by marnovo** [comment]
Or @vmarkovtsev, but you should have permissions over the blog. Ask for it
on issues-general.
