### ISSUE TITLE
Slack form on blog does not work

### ISSUE THREAD

**Issue by marnovo** [src-d/blog#139]
When filling the form with an email address and clicking the button the button is disabled but no success or failure message is displayed, and the invitation doesn't go through. Happens to both top and bottom forms.

**Comment by erizocosmico** [comment]
More info: failure on JS side related to analytics stuff.

**Comment by dpordomingo** [comment]
@vmarkovtsev could you close this issue after merging https://github.com/src-d/blog/pull/144

**Comment by erizocosmico** [comment]
You can add “Closes #issueid” to the PR and it’s done automatically.
On Wed, 25 Oct 2017 at 21:27, David <notifications@github.com<mailto:notifications@github.com>> wrote:

@vmarkovtsev<https://github.com/vmarkovtsev> could you close this issue after merging #144<https://github.com/src-d/blog/pull/144>
