### ISSUE TITLE
Remove HTML code from old posts

### ISSUE THREAD

**Issue by dpordomingo** [src-d/blog#141]
There are a lot of posts having HTML code inside, what is not allowed

Since we're trying to have a maintainable blog and being able to redesign it easily we decided to forbid HTML code inside the blog posts after the redesigned. Instead of HTML code, it must be used the available `shortcodes` for the blog, that can be found in the [README.md](https://github.com/src-d/blog/blob/master/README.md)

we could:
- create new snippets for some interesting layouts
- drop other ones that are not valuable

List of posts having HTML code in its content
![image](https://user-images.githubusercontent.com/2437584/31660637-56068a26-b338-11e7-8ec3-1ef5eeddd678.png)

**Comment by vmarkovtsev** [comment]
@dpordomingo The old posts must be updated, it's the upcoming one only.

**Comment by marnovo** [comment]
@vmarkovtsev where are the interns who were updating this? :trollface:

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because I think it will be considered during the migration :massage_woman:
