### ISSUE TITLE
Tab vs spaces uses external content hosted at github, but served in an uncommon way

### ISSUE THREAD

**Issue by dpordomingo** [src-d/blog#147]
The https://blog.sourced.tech/post/tab_vs_spaces article uses content hosted at http://content.blog.sourced.tech/tabs_spaces/index.html from https://github.com/src-d/tab-vs-spaces repository

It should be considered to migrate to a `codepen` shortcode

**Comment by dpordomingo** [comment]
@rporres Should we be aware of any infra concern like maintainability of this custom domain or so?

```shell
$> host content.blog.sourced.tech
content.blog.sourced.tech is an alias for c.storage.googleapis.com.
c.storage.googleapis.com is an alias for storage.l.googleusercontent.com.
storage.l.googleusercontent.com has address 216.58.201.144
storage.l.googleusercontent.com has IPv6 address 2a00:1450:4003:804::2010
```

**Comment by vmarkovtsev** [comment]
@dpordomingo This is a very buzzed post, and the link appears on many 3rd party sites. At least do a redirect from the old address. Are you sure that codepen can hold a 10k/hour? I guess they will rate limit - and this will be common in future posts.

**Comment by dpordomingo** [comment]
thanks @vmarkovtsev for that good feedback. We will consider that

**Comment by dpordomingo** [comment]
The post address would not changed for sure.
We will consider the codepen rate limits, thanks @vmarkovtsev for your grat feedback!!!

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because I think it will be provided by Ghost :neckbeard:
