### ISSUE TITLE
Clarify deployment process

### ISSUE THREAD

**Issue by campoy** [src-d/blog#162]
Once the code has been merged, how do I deploy the new version to production?

**Comment by vmarkovtsev** [comment]
You create the next tag and push it to master. E.g. I have created `v1.1.5` after merging #161 and it was automatically deployed.

**Comment by dpordomingo** [comment]
@campoy here is de how to :)

**Comment by dpordomingo** [comment]
@campoy here is de how to :)
https://github.com/src-d/guide/pull/70

**Comment by dpordomingo** [comment]
S

**Comment by dpordomingo** [comment]
Feel free to reopen if you think the guide sould be improved, or it is not enough
