### ISSUE TITLE
On the blog page join slack button disabled Wanted to report bug also https://blog.sourced.tech/ on this page the place to enter the email id to join slack channel does not work that button does not work. OSX and chrome browser. When I press command key inside that text-box then only the button is enabled and clickable

### ISSUE THREAD

**Issue by vardhanapoorv** [src-d/blog#169]
<img width="847" alt="screen shot 2017-12-08 at 7 12 31 am" src="https://user-images.githubusercontent.com/13391028/33747004-9d2eb168-dbe6-11e7-8edf-8cce0e0f353c.png">

**Comment by dpordomingo** [comment]
Lets follow this issue in the other one https://github.com/src-d/blog/issues/168 :)
