### ISSUE TITLE
Add PDF viewer

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#170]
The blog post I am currently working on requires showing a PDF file. I talked to @dpordomingo and he confirmed there is no existing shortcut and suggested https://pdfobject.com/ as an implementation. So this is a feature request.

cc @marnovo

**Comment by dpordomingo** [comment]
I just googled for some PDF library and found that. It should be needed to analyze if that one (or any other) fits your expectations.

**Comment by vmarkovtsev** [comment]
It fits perfectly if there is a way to open the PDF in new tab.

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because I think it will be provided by Ghost :crossed_fingers:
