### ISSUE TITLE
When user right/middle clicks in a link, the link is opened in the same tab

### ISSUE THREAD

**Issue by dpordomingo** [src-d/blog#172]
Reported via tweeter https://twitter.com/hoelzro/status/937732969623642112

> @srcd_ Your blog is really interesting! Just a heads-up, though - on Firefox 57, right clicking or middle clicking on links automatically follows the link like a left click, which is a little frustrating when I'm trying to open lots of posts to read =)

**Comment by dpordomingo** [comment]
It may be a problem with GoogleAnalytics links highjacking.
I tried with Chrome, and it could not be reproduced, but I found another problem:
> Shift/Ctrl+Click should open a link in new window/tab

Once we start working in this issue, we should let the user to know about this issue :D

**Comment by smacker** [comment]
Confirm on MacOS + Safari. Cmd+Click doesn't open page in new tab. Very annoying.

**Comment by campoy** [comment]
Are we working on this?
I faced it today again and it's indeed quite annoying.

**Comment by dpordomingo** [comment]
This issue was not prioritized yet :(

**Comment by campoy** [comment]
Ok, let's try to prioritize this as it causes friction on the visitors we get

cc @marnovo
