### ISSUE TITLE
Implement social media cards

### ISSUE THREAD

**Issue by campoy** [src-d/blog#174]
Currently links to the blog post appear as simple links when posted to social media.

We should implement at least twitter and facebook cards.
A good article on the topic: https://www.koozai.com/blog/social-media/social-markup/

**Comment by dpordomingo** [comment]
That's a good point and a must-have.

Lets confirm:

**Facebook Open Graph:**
- `og:description`: article front matter description
- `og:url`: absolute url to the content
- `og:image`: article front matter image absolute url
- `og:type`: `article` (always)
- `og:site_name`: `{{.Site.Params.name}}` &rarr; will render `source{d}`

**Twitter Cards**
- `twitter:card`: article front matter title
- `twitter:site`: `@{{.Site.Params.twitter}}`
- `twitter:creator`: tweeter handler of the author

**Notice:**

About both:
- I think we should maybe confirm that `article front matter image` is what we want for facebook/tweeter cards; I mean: will they have the right aspect ratio? should we use a different image?
- should we add Facebook Open Graph and Twitter Cards metadata in blog listings?

**Comment by campoy** [comment]
I think we should use a different image, something like `social_image` but fallback to `image` when that one is not available (such as in older blog posts)

no need to add those on blog listings (if by that you mean a list of blogs such as blog.sourced.tech)

**Comment by dpordomingo** [comment]
Yes, the fallback will be needed, and it's easy to do.

Yes, I meant the blog home and it's paginations, so ok: let's consider only the articles.

**Comment by campoy** [comment]
I'd like to prioritize this too, @marnovo 
Thanks!
