### ISSUE TITLE
Remove Hotjar Tracking Code

### ISSUE THREAD

**Issue by dpordomingo** [src-d/blog#178]
We have the following tracking code in our site [themes/hugo-steam-theme/layouts/partials/js.html#L40](https://github.com/src-d/blog/blob/b956f3c515d601347bb43bcc6626c87aa77a1125/themes/hugo-steam-theme/layouts/partials/js.html#L40)
```html
<!-- Hotjar Tracking Code for //sourced.tech/ -->
<script>
   (function(h,o,t,j,a,r){
       h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
       h._hjSettings={hjid:184958,hjsv:5};
       a=o.getElementsByTagName('head')[0];
       r=o.createElement('script');r.async=1;
       r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
       a.appendChild(r);
   })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

I think we had a conversation about it in slack but it might be archived so I couldn't find it.

Could we drop this tracking script?

**Comment by dpordomingo** [comment]
@eiso might know about this

**Comment by dpordomingo** [comment]
Adding the link to the file where Hotjar appears, I realized that the [conversation was about removing adds](https://github.com/src-d/blog/commit/e30558f852a6f417ec536716648246501dc232be), not about this heat map tracking tool, [added by 21daf10](https://github.com/src-d/blog/commit/21daf104a0d442926e81024db41b4289131865da).

Feel free to reopen if it is no longer used and/or we should delete it.

**Comment by eiso** [comment]
This is with @marnovo, since he was using it to evaluate effectiveness of the site.
