### ISSUE TITLE
Feature request: filter posts by author

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#179]
I have been in need of this feature for a long time: many people ask for my posts and I cannot give a single link. Instead, I have to go through the whole blog again and again and record the links. Would be super useful to query all the posts by a specific author.

**Comment by dpordomingo** [comment]
You're right. That's a must have.
I'm not sure if that will be easy, or if it will require a small hack, but we can study it.

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because I think it will be provided by Ghost :nail_care:
