### ISSUE TITLE
write "Calling C functions from BigQuery with webassembly"

### ISSUE THREAD

**Issue by campoy** [src-d/blog#180]
Initial effort is here

- https://gist.github.com/campoy/b0d36c2c115920d2dd5c8b0188879b32

related twitter threads:
- https://twitter.com/francesc/status/951935862467514368
- https://twitter.com/francesc/status/951928798026412032

**Comment by campoy** [comment]
First draft ready on https://github.com/src-d/blog/pull/191
Also published on https://blog-staging.srcd.run/post/calling-c-functions-from-bigquery/

**Comment by campoy** [comment]
deadline: 2018/03/06

**Comment by bzz** [comment]
This seems to be fixed by https://github.com/src-d/blog/pull/191 now 🎉
