### ISSUE TITLE
Spurious bullets in minhashcuda post

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#181]
There are bullets after indices in https://blog.sourced.tech/post/minhashcuda/

![screen shot 2018-01-18 at 11 37 57](https://user-images.githubusercontent.com/2793551/35093970-2f89e71c-fc44-11e7-8e11-a596e1e37032.png)

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because it shouldn't happen in the new environment :fire:
