### ISSUE TITLE
Add social media "share" buttons on blog posts

### ISSUE THREAD

**Issue by campoy** [src-d/blog#199]
Once you're done reading a blog post, you might want to share it with your friends.
I recommend share buttons for twitter, facebook, and maybe Google+.

**Comment by dpordomingo** [comment]
Avast mine of share buttons do we want?
- at the end of every post,
- at the top,
- those ones placed on the left or right black space, that follows you as you scroll,
- those ones, pretty intrusive, that appear when you highlight something.

(Ordered from easier to more complex/intrusive)

Should we track some metrics about people using them?

@Ricardo might provide some info.

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because it won't happen in the new environment :100:

**Comment by dpordomingo** [comment]
reopening because I could not find the `share` button in new blog

**Comment by dpordomingo** [comment]
already there
