### ISSUE TITLE
Dead link to PGA in GLD post

### ISSUE THREAD

**Issue by marnovo** [src-d/blog#211]
From: https://twitter.com/maxibanki/status/995685281591386112

> Hey @sourcedtech,
> on this blog post:
> https://t.co/g5C5Js3g1k
> you are hyperlinking to a dead link to your Public Git Archive repository :)

(Sorry for the poor issue, doing this from mobile)

**Comment by vmarkovtsev** [comment]
@marnovo Do you think it is urgent enough to merge now or can wait until tomorrow evening?
