### ISSUE TITLE
[PROPOSAL] cross-post of google static analysis paper review

### ISSUE THREAD

**Issue by bzz** [src-d/blog#213]
Idea came up as a suggestion from @eiso and @campoy 

* Title: Lessons from Building Static Analysis Tools at Google
* Author(s): Alex, anyone else
* Categories: ?
* Deadlines: N/A

## Table of contents

Original https://medium.com/@seoul_engineer/paper-review-lessons-from-building-static-analysis-tools-at-google-cc71a43bdee

Changes/suggestions/contributions are welcome and co-authorship is encourage!

## Management

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

**Comment by campoy** [comment]
Great idea!
