### ISSUE TITLE
[PROPOSAL] paper review "Learning to Represent Programs with Graphs"

### ISSUE THREAD

**Issue by bzz** [src-d/blog#214]
* Title: Either a "Paper review XXX", or "Machine Learning behind MSFT IntelliCode", but may be too click-batty. Suggestions are welcome.
* Author(s): Alex, anyone else?
* Short description: Graph representation of programs though the history and overview of MSR paper  and how it became Visual Studio IntelliCode feature.
* Categories:
* Deadlines: N/A

## Table of contents
Story follows along the lines:

- history
   on the origins and inspiration of this work in the recent advances in quantum physics 
- summary of the paper
- deployment
   How it became InteliCode

## Management

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

**Comment by campoy** [comment]
I just finished this paper, looking forward to reviewing your review!
