### ISSUE TITLE
[PROPOSAL] Cheers to small beginnings!

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/blog#215]
Issue Title: [PROPOSAL] Blog post title

* Title: Cheers to small beginnings!
* Author(s): Ricardo Baeta
* Short description: A closer look at source{d}'s rebranding.
* Categories: design, branding
* Deadlines: We need to get this blog out on Q2, ideally before the [Landing's New Visual Design](https://github.com/src-d/okrs/issues/32)

### Molto vivace
The momentum around design at source{d}.

### First things first
What does the Brand Persona means, and what's to come.

### All aboard
Design as a team sport. 

### Cookin’ on three burners
Designing with a rationale based on research and Open Source Design Assets.

### Claws that can grab a dinosaur
Making reasoned design decisions.

### One, two, buckle my shoe
Where are we, and where do we want to go.

## Management

This section will be filled by @campoy.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post: [google docs draft](https://docs.google.com/document/d/15WwMtWrZaiBHa_XJzCDpUZf_etBUEPcr3JZjt-CBr0k/edit)

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

**Comment by ricardobaeta** [comment]
I don't have permissions to:

> Once you've created this issue make sure to add the post label and assign it to @campoy

**Comment by marnovo** [comment]
@campoy please review.

**Comment by campoy** [comment]
Looks good to me! Great idea

**Comment by marnovo** [comment]
Thanks! @ricardobaeta the ball is in your field, now.

**Comment by vcoisne** [comment]
Published
