### ISSUE TITLE
[PROPOSAL] Babelfish turns one!

### ISSUE THREAD

**Issue by campoy** [src-d/blog#219]
* Title: Babelfish turns one!
* Author(s): Francesc
* Short description: One year after the first version (or first announcement) of babelfish, what's going on with the project?
* Categories: bblfsh, language analysis
* Deadlines: It'd be great to publish it either on September 19th (anniversary of v1 release) or June 20th (anniversary of first announcement)

I could use @smola or @mcuadros help with this announcement.

## Table of contents

TBD but:

- history of the project
- features added since then
- roadmap
- current users

## Management

* State: proposed
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

**Comment by smola** [comment]
Once all drivers and clients are updated to the very latest protocol and UAST version, it would be a good time to make some noise again.

**Comment by campoy** [comment]
Do you know when that would be?

**Comment by smola** [comment]
@campoy _Hopefully_ within this quarter.

**Comment by campoy** [comment]
Ok, let's leave this waiting for now then and review in a month.

reminder: 2018-11-24

**Comment by campoy** [comment]
Hey @smola,  we would love to release this eventually.

Do you think someone from the @src-d/language-analysis might be able to take some time for this?

**Comment by vmarkovtsev** [comment]
How about waiting 2 more months and writing "Babelfish turns two"? As far as I remember the work began in early February...

**Comment by creachadair** [comment]
> Hey @smola, we would love to release this eventually.
> 
> Do you think someone from the @src-d/language-analysis might be able to take some time for this?

Well, I can't speak for @smola but it certainly seems like a good idea.

**Comment by smola** [comment]
@creachadair Sure, it's not your business :wink:

**Comment by creachadair** [comment]
> @creachadair Sure, it's now your business 😉

Me and my big mouth. ;)

Seriously, though, I'm happy to help out with this.

**Comment by vcoisne** [comment]
@creachadair it would be awesome if you could help with this. I know @campoy is swamped. 

We want to make sure we position babelfish in the post has a core component of the Engine though.

**Comment by creachadair** [comment]
> @creachadair it would be awesome if you could help with this. I know @campoy is swamped.
> 
> We want to make sure we position babelfish in the post has a core component of the Engine though.

Sounds good. What are we using as the actual date? I see @vmarkovtsev suggests early February, but the issue was filed in June.

**Comment by vcoisne** [comment]
@creachadair looking at the bblfh repo looks like first release was in June 2017 so I suggest we aim for June 2019 and do Babelfish turns 2 :) cc @campoy

**Comment by creachadair** [comment]
> @creachadair looking at the bblfh repo looks like first release was in June 2017 so I suggest we aim for June 2019 and do Babelfish turns 2 :) cc @campoy

Sounds good to me. Feel free to assign it to me, since I don't appear to have the permissions to do so.

**Comment by vcoisne** [comment]
@creachadair let me know if that's still something you're interested in writing about ?

**Comment by creachadair** [comment]
Sure, I'm game. We should update the title from "one" to "two", or maybe I will just start a new issue and close this one in favour of it (since I still can't edit this one).

**Comment by creachadair** [comment]
Since time's closing in, I'll put together an outline this week.

**Comment by vmarkovtsev** [comment]
Hehe :) Babelfish turns three?

**Comment by creachadair** [comment]
I didn't finish this, but I don't think we have to wait a whole year. Maybe just "Babelfish in review".

**Comment by vcoisne** [comment]
That's a good idea @creachadair when do you think you'll have time to write something up ?
