### ISSUE TITLE
[PROPOSAL] How I spoke on 9 conferences in 2 months

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#220]
I want to describe my experience, what I have learned, funny failures (OSCAL) and big wins (dotAI). Give tips to the beginning speakers since I used to be one a short time ago. Tell the MLonCode story, how it evolved within two years. Disclose the beautiful and ugly sides of the show business haha.

**Comment by vmarkovtsev** [comment]
@campoy ping

**Comment by vcoisne** [comment]
+1 @vmarkovtsev I'm sure this would be of interest to many people in the community!

**Comment by campoy** [comment]
I was gonna ask you to follow the template, but you explained quite well the contents, so I'm ok with this.

Before we continue, please provide which audience is your target and what would be their take aways.

**Comment by vcoisne** [comment]
@vmarkovtsev is that still something you want to write about ?

**Comment by vmarkovtsev** [comment]
Definitely, its on my list and I've been thinking much about it. Once I pass through this MSR-PlC-Fosdem grind I will write it.

**Comment by vmarkovtsev** [comment]
Done: https://blog.sourced.tech/post/how-it-conferences-can-be-better-for-speakers/
The concept has evolved a bit.
