### ISSUE TITLE
[PROPOSAL] Identifier splitter

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#221]
* Title: Splitting source code identifiers
* Author(s): Vadim
* Short description: This is supposed to present our [paper](https://arxiv.org/abs/1805.11651) which was accepted to ML4P.
* Categories: technical, mloncode, science
* Deadlines: no deadlines

## Table of contents

TODO

## Management

This section will be filled by @campoy.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

**Comment by vmarkovtsev** [comment]
@campoy ping

**Comment by campoy** [comment]
Please use [this template](https://github.com/src-d/blog/blob/master/.github/ISSUE_TEMPLATES/post.md) for the issue.
I'm not sure why it was not suggested by GitHub directly 😕

**Comment by vmarkovtsev** [comment]
Done

**Comment by campoy** [comment]
Thanks, but the table of contents is actually quite important 😄 
It doesn't need to be definitive, but it should help us structure the talk and see what content would be included.

**Comment by vmarkovtsev** [comment]
Presentation: http://vmarkovtsev.github.io/ml4p-2018-oxford

**Comment by campoy** [comment]
SGTM, accepted
