### ISSUE TITLE
[FEATURE] Add the date when the blog post was published

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#222]
It is what it is: add the date somewhere at the header or the footer of each post record on the main page.

**Comment by vcoisne** [comment]
How do people feel about using Medium instead as our blogging platform? That would solve this issue + add many benefits ?

cc @marnovo @campoy ?

**Comment by vmarkovtsev** [comment]
We used to discuss it and it boiled down to converting the existing 42 posts from Hugo Markdown + many custom shortcodes to Medium. E.g. this post is much fun to convert https://blog.sourced.tech/post/lapjv/

**Comment by vcoisne** [comment]
I see how that would require some work :) 

I still think it would be worth it.
