### ISSUE TITLE
Error reporting in case of non-existent author

### ISSUE THREAD

**Issue by bzz** [src-d/blog#229]
**Describe the bug**

`make serve` swallows the error in case an author of blog post is not in the `authors.yml` and the blog post is silently not served.

Only running `make hugo-server` reveals the error:
```
ERROR 2018/07/25 13:07:10 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "skeleton" (...>: error calling partial: template: theme/partials/skeleton.html:7:7: executing "theme/partials/skeleton.html" at <partial (printf "ske...>: error calling partial: template: theme/partials/skeleton-single.html:15:15: executing "theme/partials/skeleton-single.html" at <partial "author" $ct...>: error calling partial: template: theme/partials/author.html:24:36: executing "theme/partials/author.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
```

**To Reproduce**
 1. create new blog post with a new, non-existent author
 1. `make serve`
 1. visit blog post URL

**Expected behavior**
 - error in CLI on `make serve`

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because it won't happen in the new environment :dancer:
