### ISSUE TITLE
shortcode request: horizontal separator

### ISSUE THREAD

**Issue by bzz** [src-d/blog#230]
Sometimes, it's useful to have some visual (and semantic) horizontal content separator inside the article i.e center-aligned ellipsis as Medium implement it with [Horizontal Rule](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)

**Screenshots**

Example from Medium

---------------------

<img width="751" alt="screen shot 2018-07-26 at 12 23 29 pm" src="https://user-images.githubusercontent.com/5582506/43256980-ba9b4908-90ce-11e8-9427-213a82bce27d.png">

---------------------

It would be nice to be able to do that with i.e something like

```
{{% separator %}}
```

Using a workaround for now

```
{{% center %}} … {{% /center %}}
```

**Comment by dpordomingo** [comment]
Easy to develop.
Does @marnovo approve it?

**Comment by vcoisne** [comment]
my 2cents is that we should not be developing our own blog platform. I created an issue  [https://github.com/src-d/devrel/issues/83](url) to discuss migrating over to Ghost.

**Comment by vcoisne** [comment]
@marnovo can we close all the issue that are feature requests related to the legacy Hugo blogging platform?

**Comment by dpordomingo** [comment]
The migration to the new blogging platform is almost completed, so we're closing this issue because it will be most likely provided by Ghost :dancer:

**Comment by bzz** [comment]
> will be most likely provided by Ghost

does anyone have any idea how likely this feature is going to be provided? :)

**Comment by vcoisne** [comment]
It is an existing feature in Ghost @bzz
