### ISSUE TITLE
[PROPOSAL] Hercules v4

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#235]
* Title: What's new in Hercules v4
* Author(s): Vadim
* Short description: The post should describe the cool features of src-d/hercules which appeared after [v1](https://blog.sourced.tech/post/hercules/)
* Categories: technical, science
* Deadlines: none

## Table of contents

Modern Hercules is able to:

1. Process the **whole** commit history DAG, not just the main sequence. It was very hard to implement, there were very funny and unique problems to solve, many insights into how Git works, very hardcore.
2. Load plugins. A few words about how Go plugins work.
3. Merge the results from several repositories together.
4. Use UASTs for deeper analysis, e.g. structural hotness.
5. Work with siva.

There will be cool pictures with the analysis results. Also some notes on common code snippets which were not idiomatic Go and are fixed now. + some notes on the project structure evolution, how I went from flat to tree and [defined the public interface using type aliases](https://github.com/src-d/hercules/blob/master/core.go).

## Management

This section will be filled by @campoy.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

*NOTE* Please write in short lines so the review is easier to do.

**Comment by campoy** [comment]
Totally down for this (and thanks for using the template!)

Is v4 already released? Maybe we could sync both the release and this blog post.

**Comment by vmarkovtsev** [comment]
It is silently released - I want to announce it properly.

**Comment by campoy** [comment]
Sounds good, this can easily become a great talk too.

The new hercules v4 works on top of gitbase?

**Comment by vmarkovtsev** [comment]
Nope, it is pure go-git. Works with `git.Repository` wherever it comes from.

**Comment by eiso** [comment]
We discussed about exposing Hercules analysis through UDFs in gitbase
