### ISSUE TITLE
Add CORS policy to staging

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#240]
There is no `Access-Control-Allow-Origin` header in the staging server response. If this is a bug and not a feature then it would be cool to add the `*` policy.

How about blog.sourced.tech btw?

**Comment by dpordomingo** [comment]
How did you discover that? Would you like to access blog content (or JSON feeds) via AJAX?

**Comment by vmarkovtsev** [comment]
@dpordomingo I want to use [Tensorflow Projector](http://projector.tensorflow.org/) which loads a JSON config and the data files by HTTP.

**Comment by vmarkovtsev** [comment]
An alternative is to host our own projector on blog.sourced.tech.

**Comment by dpordomingo** [comment]
this might help you
https://github.com/src-d/blog/pull/243

**Comment by dpordomingo** [comment]
@vmarkovtsev It was deployed into Production within the new release [v1.17.1](https://github.com/src-d/blog/releases/tag/v1.17.1)
Feel free to reopen this issue if you suffer from cors again while fetching blog from Tensorflow Project
