### ISSUE TITLE
[PROPOSAL] How to build your own Lookout Analyzers

### ISSUE THREAD

**Issue by vcoisne** [src-d/blog#249]
* Title: How to build your own Lookout Analyzers
* Author(s): Victor & others
* Short description: Lookout Intro, analyzers intro and How to create your own Lookout Analyzer
* Categories: Lookout
* Deadlines: ASAP but not urgent

## Table of contents

1. What's Lookout
2. What are the existing analyzers 
3. How to build your own

## Management

This section will be filled by @campoy.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

*NOTE* Please write in short lines so the review is easier to do.

**Comment by bzz** [comment]
@vcoisne looks great, please let me know if you need any help with this one - I have created few analyzers in Python and Go before 😆

**Comment by bzz** [comment]
@campoy 
> I would like to make sure this also becomes a piece of our docs.

Right now the closest approximation is https://github.com/src-d/lookout/tree/master/sdk#developing-an-analyzer

**Comment by vcoisne** [comment]
@campoy I have added a draft to ghost for review

**Comment by dpordomingo** [comment]
@vcoisne is that draft accessible for review?

**Comment by vcoisne** [comment]
Published https://blog.sourced.tech/post/what-are-source-d-lookout-analyzers-and-how-to-create-one/
