### ISSUE TITLE
Lincense change

### ISSUE THREAD

**Issue by mcuadros** [src-d/blog#260]
Base on our guide the MIT license is not one option so should be changed:
https://github.com/src-d/guide/blob/master/engineering/licensing.md

**Comment by campoy** [comment]
I propose using Creative Commons BY-SA 4.0, since the licensing guidelines actually say that's the license of the blog.

**Comment by dpordomingo** [comment]
I think it should be a mixed license: CC for editorial content, and a proper license for the software itself like GPL

**Comment by dpordomingo** [comment]
**CC BY-SA 4** and **GPL v3** are [one-way compatible](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/), but I'm not sure if that help us.

I wonder if adding an extra CC-BY-SA LICENSE file inside [blog/content](https://github.com/src-d/blog/tree/master/content) would be enough to keep that part as CC, and the rest of the repo as GPL v3

**Comment by campoy** [comment]
Could you send a PR for this? I could do that too later, but I need to prepare a meetup today

**Comment by dpordomingo** [comment]
done by https://github.com/src-d/blog/pull/264
