### ISSUE TITLE
[PROPOSAL] Formatting. With style.

### ISSUE THREAD

**Issue by m09** [src-d/blog#268]
* Title: Formatting. With style.
* Author(s): Hugo and interested members of the ML team
* Short description: Describe the current style analyzer and the future plans for a deep learning version of this same analyzer.
* Categories: deep learning, unsupervised learning, meta learning, machine learning on code, machine learning, source code formatting, lookout
* Deadlines: no deadline

## Table of contents

- Problem statement: why linters are not enough. What we accomplish in format analyzer (model the existing style in a repo and use it to lint new code).
- A first solution: unsupervised learning. This section will describe our current analyzer. It will already be really beefy since we have many tweaks and hacks to explain. Roughly:
    - Circumventing a lack of data with carefully selected features and unsupervised learning
    - How to do interpretable unsupervised learning: from decision trees to rules.
    - Polishing: hyper-parameter tuning, output checks with babelfish, performance analysis.
- The future: meta-learning. This section will describe the plans we have to go beyond unsupervised learning and use deep learning techniques to obtain a very robust and more expressive model. Roughly:
    - What is meta-learning and why is it useful here?
    - Our model
    - Connection to other successful approaches (auto-encoders, encoder decoder, VAEs, etc).
- Conclusion, links

## Management

This section will be filled by @campoy.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

*NOTE* Please write in short lines so the review is easier to do.

**Comment by campoy** [comment]
This sounds amazing! Looking forward to reading the first draft 😄

**Comment by vcoisne** [comment]
@m09 Did you get a chance to start a draft ?

**Comment by campoy** [comment]
Hey, @m09 we would love to publish this ASAP to use the momentum from the release.

When do you think you'd have time to work on this?

**Comment by vcoisne** [comment]
This has been published per https://github.com/src-d/blog/pull/273
