### ISSUE TITLE
Links from the blog archive lead to the new blog

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#284]
Posts from the blog archive link to the new blog.

**Comment by dpordomingo** [comment]
should be fixed by https://github.com/src-d/blog/pull/285
But I a review before merging and deploying it...

**Comment by dpordomingo** [comment]
@vmarkovtsev the issue with archived blog pointing to new one was already fixed, and not it points to archived posts ;)
https://blog-archive.sourced.tech/
