### ISSUE TITLE
hercules.v4 was ported as hercules-v4

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#288]
I found that there is one URL which does not map to the old id: hercules.v4 was mapped to hercules-v4.

**Comment by vmarkovtsev** [comment]
Fixed this myself.

cc @vcoisne

**Comment by vmarkovtsev** [comment]
Actually, it is impossible to have a dot in the slug. So even if I update, I still get a dash.

I had to change all the pointing links in the READMEs, presentations, etc.

**Comment by vcoisne** [comment]
Thanks a lot @vmarkovtsev, really appreciate your help!
