### ISSUE TITLE
Update blog header and footer

### ISSUE THREAD

**Issue by vcoisne** [src-d/blog#292]
We need to update the header and footer of blog.sourced.tech based on https://github.com/src-d/landing/pull/405

**Comment by znegrin** [comment]
I guess that we should wait until the new landing is online to do this, or the links will be broken.

**Comment by vcoisne** [comment]
correct @znegrin

**Comment by znegrin** [comment]
The blog is now updated with the new header and footer:

![image](https://user-images.githubusercontent.com/14981468/60293656-f3831200-991f-11e9-9311-8af380051269.png)

**Comment by vcoisne** [comment]
Thank you @znegrin closing.
