### ISSUE TITLE
[PROPOSAL] gitlab paper

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#294]
* Title: TBD, short paper review: Identifying collaborators in large codebases
* Author(s): Vadim, ?
* Short description: https://arxiv.org/abs/1905.06782
* Categories:
* Deadlines: ?

## Table of contents

TODO

## Management

This section will be filled by ~@campoy~.

* State: (proposed | writing | written | published)
* Scheduled:
* Link to post:

## Social Media

* Wording for tweet:
* Hashtags:
* Subreddits:

*NOTE* Please write in short lines so the review is easier to do.

**Comment by campoy** [comment]
Feel free to remove my name from the template, so I don't get notified every time :)

**Comment by vcoisne** [comment]
Here is the [draft](https://docs.google.com/document/d/1NHUqpm6bdxHdJFg4zMMG7QcLItC1Mi94jI8NRyoDUyg/edit?ts=5d2e36c9)

Please review @vmarkovtsev @warenlg @m09 and others

**Comment by vcoisne** [comment]
Published. https://blog.sourced.tech/post/identifying-collaboration-in-large-codebases/
