### ISSUE TITLE
[PROPOSAL] MSR 2019 Recap

### ISSUE THREAD

**Issue by m09** [src-d/blog#304]
* Author(s): TBD, cf https://github.com/src-d/ml-backlog/issues/55
* Short description: Recap of the Montreal event
* Categories: MSR 2019, MLonCode
* Deadlines: TBD
* Link to draft in google doc:

**Comment by vcoisne** [comment]
@m09 @vmarkovtsev @warenlg TBH I think it's a bit too late to do a recap. I would focus on the other ones and cancal this one. WDYT ?

**Comment by vcoisne** [comment]
Too many posts already in the works. This one is not priority. Closing.
