### ISSUE TITLE
Move margin from article.post to inner tags

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#90]
I want to have the margin in the inner tags so images can be wider than 600px.

**Comment by vmarkovtsev** [comment]
My hacky workaround:

```html
<div id="whatever">
<!-- converted Markdown here - the parser does not accept it inside HTML tags -->
</div>

<style>
#whatever {
  width: 1000px;
  margin-left: -200px;
}
</style>
```

**Comment by dpordomingo** [comment]
It was already solved with the `grid` shortcode
https://github.com/src-d/blog/blob/master/themes/hugo-steam-theme/static/css/screen.css#L817

You can obtain a 1000px container doing:
```
{{% grid %}}
This container has extra-width
{{% /grid %}}
```

If it suits you, please close this issue :) (I can not do it)

**Comment by dpordomingo** [comment]
If https://github.com/src-d/blog/issues/90#issuecomment-340595442 does not suit you, feel free to reopen the issue :D
