### ISSUE TITLE
kallax blog post: nullable types

### ISSUE THREAD

**Issue by smacker** [src-d/blog#92]
> Finally, no other ORM we’ve found saves you from using things like sql.NullInt64, which in the end ruled them all out.

One of the most popular ORMs supports pointers for years. It's very strange to see that you couldn't find it:
https://github.com/jinzhu/gorm/blob/master/pointer_test.go

**Comment by erizocosmico** [comment]
They do use `sql.NullInt64` in the docs (http://jinzhu.me/gorm/models.html) so we kind of assumed it didn't have support for pointers.

**Comment by smacker** [comment]
we use pointers quite often in our project. Also it's recommended way to deal with nullable types, even it's not reflected in documentation: https://github.com/jinzhu/gorm/issues/1057

**Comment by bzz** [comment]
Would this discussion benefit from moving it to an issue in src-d/kallax ?

If no objections, closing this issue in blog for now but please, feel free to re-open if feel that it's more relevant to have it here.
